algoritmo "Exercicio - Consumo"
// Função :
// Autor : Diego
// Data : 01/02/2024
// Seção de Declarações 
var
    distanciaPrecorrida, consumoMedio:real
    combustivel:real
inicio
  escreva("Distância percorrida: ")
  leia(distanciaPrecorrida)
  escreva("Combustivel:")
  leia(combustivel)
  
  consumoMedio <- distanciaPrecorrida / combustivel
  
  escreva("Consumo médio: " , consumoMedio)

  
fimalgoritmo
