algoritmo "Teste Estrutura condicional."
// Função :
// Autor : Diego
// Data : 13/02/2024
// Seção de Declarações 
var
   hora:real
inicio

  escreval("Digite hora:")
  leia(hora)
  se hora < 12 entao
    escreval("Bomdia")
     senao
          se (12 <= hora) e  (hora < 18) entao
             escreval("Boa tarde")
             senao
                  escreval("Boa noite")
          fimse


  fimse
fimalgoritmo
